version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: runner
    container_name: medical-app-frontend-dev
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - medical-app-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: medical-app-backend-dev
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PORT=8080
      - DATABASE_URL=sqlite:///./medical.db
      - JWT_SECRET=dev-secret-key-change-in-production
      - ENVIRONMENT=development
    volumes:
      - ./medical.db:/app/medical.db
    networks:
      - medical-app-network
    restart: unless-stopped

networks:
  medical-app-network:
    driver: bridge
